//! `bindings/ladder.ts`: the attention ladder's one schedule (`table_attention::LADDER`) as a
//! value, so the Tumbler page and the browser mock read the same rungs Rust runs on instead of
//! copying them (attention-ladder-1).
pub fn typescript() -> Result<String, serde_json::Error> {
    Ok(format!(
        "// Generated by `cargo run -p table-client --bin generate-bindings` from\n\
         // table_attention::LADDER. Do not edit: change the schedule in Rust.\n\
         import type {{ LadderSchedule }} from \"./LadderSchedule\";\n\n\
         export const LADDER: LadderSchedule = {};\n",
        serde_json::to_string_pretty(&table_attention::LADDER)?
    ))
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    #[test]
    fn every_field_of_the_schedule_is_exported_with_its_value() {
        let ts = super::typescript().unwrap();
        let value = serde_json::to_value(table_attention::LADDER).unwrap();
        for (key, v) in value.as_object().unwrap() {
            assert!(ts.contains(&format!("\"{key}\": {v}")), "{key}");
        }
    }
}
