//! `bindings/playbooks.ts`: the role playbooks, word for word, so a run's details can show the
//! owner exactly what an agent app was told. Generated from the same compiled-in text the native
//! engine writes as its system prompt (`table_core::Playbook`), so the two never differ.
use table_core::Playbook;

pub fn typescript() -> Result<String, serde_json::Error> {
    let mut out = String::from(
        "// Generated by `cargo run -p table-client --bin generate-bindings` from prompts/*.md\n\
         // (table_core::Playbook). Do not edit: change the prompt file.\n\
         import type { Playbook } from \"./Playbook\";\n\n\
         export const PLAYBOOKS: Record<Playbook, string> = {\n",
    );
    for playbook in Playbook::ALL {
        out += &format!(
            "  {}: {},\n",
            playbook.name(),
            serde_json::to_string(playbook.text())?
        );
    }
    out += "};\n";
    Ok(out)
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    #[test]
    fn every_playbook_is_exported_under_its_wire_name() {
        let ts = super::typescript().unwrap();
        for playbook in table_core::Playbook::ALL {
            let wire = serde_json::to_value(playbook).unwrap();
            assert_eq!(wire, playbook.name());
            assert!(ts.contains(&format!("  {}: \"", playbook.name())));
        }
    }
}
