// The client contract: Rust owns these types (bindings/, generated by ts-rs, drift-tested).
// This file only derives helper types from them; never redefine a wire shape here.
import type { CommandContract } from '@bindings/CommandContract';
import type { EventContract } from '@bindings/EventContract';
import type { CommandError } from '@bindings/CommandError';
import type { ErrorCode } from '@bindings/ErrorCode';

export type WindowLabel = 'main' | 'tumbler' | 'approval';

/** Every command comes from the generated Rust contract. */
export type AllCommands = CommandContract;
export type CommandName = keyof AllCommands;
export type ArgsOf<K extends CommandName> = AllCommands[K]['args'];
export type ResultOf<K extends CommandName> = AllCommands[K]['result'];

export type EventName = keyof EventContract;
export type PayloadOf<E extends EventName> = EventContract[E];

export interface InvokeOptions {
  /** Approval-window capability token. Kept in memory only, never persisted, never in a body. */
  token?: string;
}

/** Every IPC entry point goes through this interface: the Tauri shell or the browser mock. */
export interface Backend {
  readonly kind: 'tauri' | 'mock';
  readonly label: WindowLabel;
  invoke<K extends CommandName>(cmd: K, args: ArgsOf<K>, opts?: InvokeOptions): Promise<ResultOf<K>>;
  listen<E extends EventName>(event: E, cb: (payload: PayloadOf<E>) => void): Promise<() => void>;
}

/** A typed failure from Rust. UNAVAILABLE and UNSUPPORTED are states to render, not crashes. */
export class WalletError extends Error {
  readonly code: ErrorCode;
  constructor(err: CommandError) {
    super(err.message);
    this.name = 'WalletError';
    this.code = err.code;
  }
  /** The command exists but its executor/dependency is not attached yet (or not on this OS). */
  get isAvailabilityState(): boolean {
    return this.code === 'UNAVAILABLE' || this.code === 'UNSUPPORTED';
  }
}

const CODES: readonly ErrorCode[] = ['LOCKED', 'PERMISSION', 'REFUSED', 'INVALID', 'NOT_FOUND', 'UNAVAILABLE', 'LEDGER_TRUST', 'UNSUPPORTED'];

/** Normalise whatever invoke rejected with into a WalletError. */
export function toWalletError(e: unknown): WalletError {
  if (e instanceof WalletError) return e;
  if (e && typeof e === 'object' && 'code' in e && 'message' in e) {
    const { code, message } = e as { code: unknown; message: unknown };
    if (typeof code === 'string' && (CODES as readonly string[]).includes(code)) {
      return new WalletError({ code: code as ErrorCode, message: String(message) });
    }
  }
  // An unregistered command (e.g. a pending extension against an older shell) or a transport
  // failure: present it as UNAVAILABLE so the UI degrades instead of breaking.
  const message = typeof e === 'string' ? e : e instanceof Error ? e.message : 'unknown IPC failure';
  return new WalletError({ code: 'UNAVAILABLE', message });
}
