// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSlot } from "./AgentSlot";
import type { EngineId } from "./EngineId";
import type { MandateId } from "./MandateId";

export type AgentRosterEntry = { slot: AgentSlot, engine: EngineId, 
/**
 * Fixed Rust text: what this slot is for.
 */
does: string, 
/**
 * Active mandates whose signed agent key is this slot's.
 */
mandates: Array<MandateId>, running: number, };
