// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalDraft } from "./ApprovalDraft";
import type { ApprovalTarget } from "./ApprovalTarget";
import type { DealId } from "./DealId";

/**
 * What the approval window was opened for, read by that window only. `target` null means owner
 * configuration (the legacy `deal_id: null` open).
 */
export type ApprovalHandoff = { target: ApprovalTarget | null, deal_id: DealId | null, draft: ApprovalDraft | null, };
