// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalDraft } from "./ApprovalDraft";
import type { ApprovalTarget } from "./ApprovalTarget";
import type { DealId } from "./DealId";
import type { H256 } from "./H256";

export type ApprovalOpenArgs = { deal_id: DealId | null, pairing?: H256 | null, 
/**
 * What the window opens on. Absent: a deal, a pairing, or owner configuration, as before.
 */
target?: ApprovalTarget | null, 
/**
 * Main's pre-fill. A suggestion only: the approval window shows it, the owner may change it,
 * and Rust re-checks and signs it there. Main never signs.
 */
draft?: ApprovalDraft | null, };
