// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Deal } from "./Deal";
import type { DealEvidence } from "./DealEvidence";
import type { H256 } from "./H256";

export type ApprovalSummary = { deal: Deal, evidence: DealEvidence, attempt: number, terms_hash: H256, counter_hash?: H256 | null, can_owner_accept?: boolean, locked: boolean, can_release: boolean, can_open_paypal: boolean, unavailable_reason: string | null, };
