// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable identity of a checklist line. The order of this enum is the order of the list.
 */
export type ApprovalCheckId = "amount" | "payee" | "host" | "invoice" | "shield" | "mandate";
