// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemRef } from "./ItemRef";
import type { MandateId } from "./MandateId";
import type { Money } from "./Money";
import type { RescueLever } from "./RescueLever";

/**
 * A draft carried from Main to the approval window. Closed shapes and typed values only.
 */
export type ApprovalDraft = { "type": "band", floor: Money | null, ceiling: Money | null, } | { "type": "floor", mandate_id: MandateId, item_ref: ItemRef, floor: Money, } | { "type": "lever", lever: RescueLever, };
