// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalCheckId } from "./ApprovalCheckId";
import type { ApprovalCheckStatus } from "./ApprovalCheckStatus";

/**
 * One line of the checklist. `text` is plain words for the owner (no ids, no clause numbers);
 * `detail` is the Layer-2 fact behind it and may name clauses, hosts and ids.
 */
export type ApprovalCheck = { id: ApprovalCheckId, status: ApprovalCheckStatus, text: string, detail: string, };
