// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttentionItem } from "./AttentionItem";
import type { Currency } from "./Currency";
import type { ExposureView } from "./ExposureView";
import type { ForecastLine } from "./ForecastLine";

export type AttentionSnapshot = { items: Array<AttentionItem>, stopped_today: number, in_motion: number, wallet_spend_today_minor: number, wallet_spend_today_currency?: Currency | null, engine_estimate_today_usd: number, locked: boolean, forecast?: Array<ForecastLine> | null, exposure?: ExposureView | null, };
