// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttnKind } from "./AttnKind";
import type { ClauseRef } from "./ClauseRef";
import type { Currency } from "./Currency";
import type { DealId } from "./DealId";
import type { Mode } from "./Mode";
import type { Module } from "./Module";
import type { TumblerAction } from "./TumblerAction";
import type { Urgency } from "./Urgency";

export type AttentionItem = { deal_id: DealId, label: string, kind: AttnKind, module: Module, headline: string, amount_minor: number, currency: Currency, counterparty: string | null, clause: ClauseRef | null, deadline: number | null, on_silence: string, urgency: Urgency, mode: Mode, actions: Array<TumblerAction>, };
