// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";
import type { DealState } from "./DealState";
import type { DecidedBy } from "./DecidedBy";

/**
 * One verified audit row, projected to closed facts: who, what, when, which deal, and the typed
 * decision and transition the row records. The row's free detail never crosses IPC.
 */
export type AuditRow = { seq: number, at: number, actor: string, action: string, deal_id: DealId | null, decided_by: DecidedBy | null, from: DealState | null, to: DealState | null, };
