// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A page of the audit chain for Book, newest first. `before` is an exclusive sequence number
 * (absent = from the newest); `limit` is 1 to 200.
 */
export type AuditPageArgs = { before?: number | null, limit: number, };
