// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";
import type { Money } from "./Money";

export type BandArgs = { deal_id: DealId, floor: Money | null, ceiling: Money | null, };
