// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookQuery } from "./BookQuery";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Aggregate rows, grouped by currency and mode first: amounts in minor units, market distance in
 * basis points. Read on a read-only connection; nothing is written.
 */
export type BookAnswer = { query: BookQuery, rows: Array<JsonValue>, };
