// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookFilter } from "./BookFilter";
import type { BookGroup } from "./BookGroup";
import type { BookMetric } from "./BookMetric";
import type { BookRange } from "./BookRange";
import type { BookView } from "./BookView";

export type BookQuery = { view: BookView, metrics: Array<BookMetric>, filters: Array<BookFilter>, group_by: Array<BookGroup>, range: BookRange | null, limit: number | null, };
