// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BookField = "kind" | "state" | "counterparty" | "amount" | "created_at" | "vs_market_pct" | "decided_by";
