// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookField } from "./BookField";
import type { BookOp } from "./BookOp";
import type { JsonValue } from "./serde_json/JsonValue";

export type BookFilter = { field: BookField, op: BookOp, value: JsonValue, };
