// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * The owner's read-only Book query. `query` is a closed BookQuery, taken raw so that a rejection
 * (schema or rule) comes back as INVALID with the reason verbatim; it is never SQL.
 */
export type BookQueryArgs = { query: JsonValue, };
