// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MandateId } from "./MandateId";

export type ClauseRef = { mandate_id: MandateId, number: number, };
