// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type-level command signature. The shell receives non-null arguments under `args`.
 */
export type Command<A, R> = { args: A, result: R, };
