// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a counterparty's identity was pinned: all four words confirmed by the owner, the HOUSE
 * seller's release-pinned key, or a key on file with no owner confirmation.
 */
export type CounterpartyPairing = "words_confirmed" | "house_pinned" | "unpaired";
