// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";

/**
 * A counterparty's own words from a signed NOTE: untrusted, quarantined plain text. Length-capped,
 * never parsed, never given to an agent or the Tumbler; only the main window reads it.
 */
export type CounterpartyNote = { deal_id: DealId, seq: number, at: number, text: string, };
