// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CounterpartyPairing } from "./CounterpartyPairing";
import type { KeyId } from "./KeyId";
import type { PayeeRef } from "./PayeeRef";

export type CounterpartyDisplay = { key_id: KeyId, display_name: string, house: boolean, first_seen: number, deals_closed: number, pairing: CounterpartyPairing, 
/**
 * The payee the counterparty declared in its signed pairing identity (a closed identifier,
 * never prose). Settlement checks it again; this is the fact, not a permission.
 */
declared_payee: PayeeRef | null, };
