// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyId } from "./KeyId";

export type CpRule = { "type": "pinned", keys: Array<KeyId>, } | { "type": "paired" } | { "type": "house" } | { "type": "subscribers" };
