// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects native credential UI. No IPC argument or result can contain a secret.
 */
export type CredentialArgs = "paypal_sandbox" | "channel3";
