// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialArgs } from "./CredentialArgs";

/**
 * Whether a credential is in the OS keyring and when it was stored. Never the secret.
 */
export type CredentialFact = { kind: CredentialArgs, stored: boolean, 
/**
 * Null when stored before this was recorded, or not stored.
 */
stored_at: number | null, };
