// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explicit supported ISO codes. Adding a currency requires its minor-unit exponent.
 */
export type Currency = "USD" | "EUR" | "GBP" | "CAD" | "AUD" | "CHF" | "NZD" | "CZK" | "SEK" | "NOK" | "DKK" | "PLN" | "JPY" | "HUF" | "KWD" | "BHD";
