// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Currency } from "./Currency";
import type { Money } from "./Money";

/**
 * Money out in one currency. Never converted: a wallet with two currencies has two rows.
 */
export type CurrencyExposure = { currency: Currency, 
/**
 * Today's deals that reached capture (part of `out_today`).
 */
paid_today: Money, 
/**
 * Authorized at PayPal right now, any day: the money is held for the payee.
 */
held: Money, 
/**
 * Agreed or cleared, not held at PayPal yet (agreed, order made, buyer approval pending).
 */
committed: Money, 
/**
 * The day's budget used: every deal that agreed today and was not released.
 */
out_today: Money, deals_today: number, };
