// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";

/**
 * The Rewind read: one deal or every deal, optionally within `[from, to)` (Unix seconds, as every
 * other timestamp in the contract).
 */
export type DealHistoryArgs = { deal_id?: DealId | null, from?: number | null, to?: number | null, };
