// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DealState = "PAIRING" | "LISTED" | "NEGOTIATING" | "AGREED" | "SETTLING" | "AWAITING_APPROVAL" | "APPROVED" | "AUTHORIZED" | "CAPTURED" | "RECEIPTED" | "RECONCILED" | "WITHDRAWN" | "EXPIRED" | "REFUSED" | "MISMATCH" | "FAILED" | "VOIDED" | "AUTO_VOIDED" | "REFUNDED" | "DISPUTED";
