// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Deal } from "./Deal";
import type { Mode } from "./Mode";

export type DealChanged = { deal: Deal, mode: Mode, };
