// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealCreateArgs } from "./DealCreateArgs";
import type { DealId } from "./DealId";

export type DealJoinArgs = { deal_id: DealId, create: DealCreateArgs, };
