// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";
import type { GroupId } from "./GroupId";
import type { GroupTable } from "./GroupTable";
import type { ItemRef } from "./ItemRef";

/**
 * A shop-around group as the owner sees it: one buyer intent, several sellers, one winner.
 */
export type DealGroupView = { group_id: GroupId, item_ref: ItemRef, opened_at: number, 
/**
 * The table that agreed; null while the sellers are still bargaining.
 */
winner: DealId | null, 
/**
 * Oldest table first.
 */
tables: Array<GroupTable>, };
