// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";

/**
 * Shop around (T8): group open buyer tables for one item, each with a different paired seller,
 * under one signed mandate. The first table to agree wins; the wallet withdraws the others with
 * a signed WITHDRAW. Grouping only restricts: it moves no money and grants nothing.
 */
export type DealGroupOpenArgs = { deal_ids: Array<DealId>, };
