// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";
import type { ReceiptEvidence } from "./ReceiptEvidence";
import type { Reconciliation } from "./Reconciliation";

export type DealEvidence = { deal_id: DealId, receipt: ReceiptEvidence, reconciliation: Reconciliation, };
