// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryStep } from "./HistoryStep";

/**
 * The newest steps, oldest first. `truncated` is set when older steps in the window were left out.
 */
export type DealHistory = { steps: Array<HistoryStep>, truncated: boolean, };
