// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { DealKind } from "./DealKind";
import type { KeyId } from "./KeyId";
import type { MandateId } from "./MandateId";
import type { Side } from "./Side";
import type { Terms } from "./Terms";

export type DealCreateArgs = { kind: DealKind, side: Side, counterparty: KeyId, mandate_id: MandateId, mandate_version: number, terms: Terms, category: Category, };
