// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";
import type { HouseRecord } from "./HouseRecord";
import type { MoneyCheck } from "./MoneyCheck";
import type { ReceiptEvidence } from "./ReceiptEvidence";
import type { Reconciliation } from "./Reconciliation";

export type DealEvidence = { deal_id: DealId, receipt: ReceiptEvidence, reconciliation: Reconciliation, 
/**
 * A money step whose PayPal outcome is not confirmed yet; null when there is none. Older
 * shells omit it.
 */
money_check?: MoneyCheck | null, 
/**
 * For a deal with the house: the house's signed record kept with the receipt and how the
 * house's later record compares with it; null otherwise. Older shells omit it.
 */
house_record?: HouseRecord | null, };
