// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";
import type { DisplayBand } from "./DisplayBand";

export type DealDisplay = { deal_id: DealId, label: string, title: string, deadline: number | null, on_silence: string | null, band: DisplayBand | null, };
