// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";
import type { DealKind } from "./DealKind";
import type { DealState } from "./DealState";
import type { DecidedBy } from "./DecidedBy";
import type { H256 } from "./H256";
import type { KeyId } from "./KeyId";
import type { MandateId } from "./MandateId";
import type { MarketRef } from "./MarketRef";
import type { Mode } from "./Mode";
import type { PaypalRefs } from "./PaypalRefs";
import type { ShieldVerdict } from "./ShieldVerdict";
import type { Side } from "./Side";
import type { Terms } from "./Terms";

/**
 * Contains no counterparty free text. Human-only evidence has a separate ledger path.
 */
export type Deal = { id: DealId, created_at?: number, updated_at?: number, kind: DealKind, side: Side, counterparty: KeyId, terms: Terms, state: DealState, mandate_id: MandateId, mandate_version: number, transcript_head: H256, paypal: PaypalRefs, mode: Mode, market: MarketRef | null, shield: ShieldVerdict | null, 
/**
 * The authority recorded with the deal's latest decision, the same value the audit log
 * carries: the owner, a rule the owner signed (a clause, the seller or HOUSE mandate), or the
 * safe default on a deadline. Absent until something decided it (and in legacy snapshots).
 */
decided_by?: DecidedBy | null, };
