// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";
import type { H256 } from "./H256";

export type DecisionArgs = { deal_id: DealId, attempt: number, terms_hash: H256, counter_hash?: H256 | null, };
