// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { H256 } from "./H256";

export type DecidedBy = { "type": "policy", clause: number, } | { "type": "human", at: number, } | { "type": "seller_mandate", mandate_hash: H256, } | { "type": "house_mandate", mandate_hash: H256, } | { "type": "safe_default", deadline: number, };
