// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Delivery = { "type": "digital_now" } | { "type": "ship_then_capture", days: number, } | { "type": "pickup_local" } | { "type": "service_on_date", unix_day: number, };
