// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Money } from "./Money";

export type DisplayBand = { floor: Money | null, ceiling: Money | null, max_rounds: number, rounds_used: number, };
