// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineId } from "./EngineId";

export type EngineProbe = { id: EngineId, 
/**
 * When this session probed the executable (null: never resolved).
 */
probed_at: number | null, available: boolean, version: string | null, detail: string | null, };
