// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineId } from "./EngineId";

export type EngineInfo = { id: EngineId, available: boolean, version: string | null, reason: string | null, };
