// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether limits are in force, as the owner's surfaces show it.
 */
export type EnvelopeStatus = "none" | "active" | "expired" | "unverified";
