// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Currency } from "./Currency";
import type { Money } from "./Money";

/**
 * The owner's wallet-wide limits to sign (T14): one currency, three numbers and an expiry. The
 * wallet picks the next version and signs with the owner key; nothing here loosens a mandate.
 */
export type EnvelopeSignArgs = { currency: Currency, max_out_day: Money, max_held: Money, max_deals_day: number, expires: number, };
