// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalSummary } from "./ApprovalSummary";
import type { AttentionSnapshot } from "./AttentionSnapshot";
import type { CommandError } from "./CommandError";
import type { DealArgs } from "./DealArgs";
import type { DealChanged } from "./DealChanged";
import type { Form } from "./Form";
import type { MainRoute } from "./MainRoute";
import type { OrientationEvent } from "./OrientationEvent";
import type { PairingPinned } from "./PairingPinned";
import type { ReceiptEvent } from "./ReceiptEvent";
import type { RunSnapshot } from "./RunSnapshot";
import type { SettingsSnapshot } from "./SettingsSnapshot";
import type { TumblerHandoff } from "./TumblerHandoff";
import type { TumblerStatus } from "./TumblerStatus";
import type { VisualState } from "./VisualState";

export type EventContract = { "tumbler:handoff": TumblerHandoff, "agent:changed": RunSnapshot, "settings:changed": SettingsSnapshot, "wallet:error": CommandError, "tumbler:visual": VisualState, "tumbler:selected": DealArgs, "attention:changed": AttentionSnapshot, "deal:changed": DealChanged, "receipt:created": ReceiptEvent, "tumbler:orient": OrientationEvent, "tumbler:form": Form, "tumbler:status": TumblerStatus, "approval:summary": ApprovalSummary, "main:route": MainRoute, "pairing:pinned": PairingPinned, };
