// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrencyExposure } from "./CurrencyExposure";
import type { EnvelopeStatus } from "./EnvelopeStatus";
import type { WalletEnvelope } from "./WalletEnvelope";

/**
 * Limits and live exposure numbers only: no deal, counterparty or key.
 */
export type ExposureView = { status: EnvelopeStatus, 
/**
 * The limits in force (or expired); null when none are signed or they did not verify.
 */
limits?: WalletEnvelope | null, 
/**
 * When the limits in force were signed (Unix seconds); null when none.
 */
signed_at?: number | null, 
/**
 * Money out per currency; empty when nothing is out.
 */
currencies: Array<CurrencyExposure>, 
/**
 * Start of today's UTC day, the window `out_today` and `deals_today` count.
 */
day_start: number, };
