// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FairPriceState } from "./FairPriceState";

/**
 * The deal's price against the market prices it was bargained on (market-data-2). Evidence
 * only: it never moves or holds money.
 */
export type FairPrice = { state: FairPriceState, 
/**
 * True when the wallet wrote this record's digest into its own record when the deal was
 * agreed; false for the latest market price of a deal not agreed yet.
 */
committed: boolean, 
/**
 * Where the deal's unit price sits among the market prices, 0 to 100; null unless
 * re-checked.
 */
percentile: number | null, 
/**
 * How many market prices the record holds; 0 for an older record.
 */
prices: number, 
/**
 * When the market prices were read; null when the committed record is missing.
 */
retrieved_at: number | null, };
