// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a deal's fair-price certificate reads after the wallet computed it again.
 */
export type FairPriceState = "rechecked" | "not_recheckable" | "broken";
