// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Currency } from "./Currency";
import type { DealId } from "./DealId";
import type { DealState } from "./DealState";
import type { ForecastAction } from "./ForecastAction";
import type { ForecastAuthority } from "./ForecastAuthority";
import type { ForecastDirection } from "./ForecastDirection";
import type { ForecastTrigger } from "./ForecastTrigger";

export type ForecastLine = { deal_id: DealId, label: string, trigger: ForecastTrigger, at: number | null, action: ForecastAction, authority: ForecastAuthority, direction: ForecastDirection, amount_minor: number, currency: Currency, end_state: DealState, 
/**
 * For a `BuyerApproves` step: the buyer's approval must reach the scheduler before this
 * time (the deal's deadline, or the end of the seller-mandate window), or the step does not
 * happen. `None` on every other line.
 */
before: number | null, };
