// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who acts. There is no owner variant: silence is the absence of an owner decision.
 */
export type ForecastAuthority = "safe_default" | "mandate_rule" | "seller_mandate";
