// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `Out` exists so the property test can prove no forecast line ever moves money out.
 */
export type ForecastDirection = "in" | "out" | "none";
