// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ForecastAction = "lapse" | "expire" | "auto_void" | "create_order" | "authorize" | "capture";
