// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";
import type { DealState } from "./DealState";
import type { KeyId } from "./KeyId";
import type { Money } from "./Money";

/**
 * One table of a shop-around group: typed, signed prices only (never the seller's words).
 */
export type GroupTable = { deal_id: DealId, counterparty: KeyId, state: DealState, 
/**
 * The seller's latest signed price (listing or counter); null before any.
 */
seller_price: Money | null, 
/**
 * Our latest signed offer; null before any.
 */
our_price: Money | null, 
/**
 * Withdrawn by the group rule because another table agreed first.
 */
closed_by_group: boolean, };
