// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaypalMethod } from "./PaypalMethod";
import type { PaypalOutcome } from "./PaypalOutcome";

export type HistoryPaypal = { "type": "none" } | { "type": "call", method: PaypalMethod, outcome: PaypalOutcome, };
