// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who decided a step, from the typed `decided_by` the chain recorded (never inferred from text).
 */
export type HistoryAuthority = { "type": "owner" } | { "type": "signed_rule", clause: number | null, } | { "type": "seller_mandate" } | { "type": "house_mandate" } | { "type": "safe_default" } | { "type": "agent_intent" } | { "type": "none" };
