// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HouseRecordState } from "./HouseRecordState";

export type HouseRecord = { state: HouseRecordState, 
/**
 * When the wallet kept the house's signed record.
 */
kept_at: number, 
/**
 * Entries in the house's record at that moment.
 */
entries: number, 
/**
 * When the wallet last compared a later record; null when it has not.
 */
checked_at: number | null, };
