// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { DealId } from "./DealId";
import type { Terms } from "./Terms";

export type HouseTable = { negotiation_deadline: number, deal_id: DealId, terms: Terms, category: Category, };
