// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the house's record compares with the signed head the wallet kept with the receipt (T9).
 * Evidence only: no state here moves or holds money.
 */
export type HouseRecordState = "kept" | "holds" | "longer" | "restarted" | "shorter" | "rewritten";
