// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The invoice's wording, fixed in the wallet: the owner sees it before approving and PayPal
 * shows it to the subscriber. Only the offer's numbers fill it; no counterparty or agent text.
 */
export type InvoiceText = { 
/**
 * The one line item's name.
 */
item: string, 
/**
 * The note to the subscriber.
 */
note: string, };
