// Generated by `cargo run -p table-client --bin generate-bindings` from
// table_attention::LADDER. Do not edit: change the schedule in Rust.
import type { LadderSchedule } from "./LadderSchedule";

export const LADDER: LadderSchedule = {
  "breathe_secs": 7200,
  "notify_secs": 900,
  "snooze_min_left_secs": 2700,
  "snooze_secs": 1800,
  "quiet_after_secs": 45,
  "quiet_opacity_percent": 55
};
