// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Seconds before a deadline (or of idleness) at which each rung of the ladder starts.
 */
export type LadderSchedule = { 
/**
 * Deadline this close or closer: the ring breathes (urgency "soon").
 */
breathe_secs: number, 
/**
 * Deadline this close or closer: the tray dot and the one OS notification (urgency "now").
 * A snoozed card comes back (pierces) at this rung.
 */
notify_secs: number, 
/**
 * Snooze is offered only while more than this is left, so a snooze always ends before the
 * notification rung.
 */
snooze_min_left_secs: number, 
/**
 * How long a snooze hides the card.
 */
snooze_secs: number, 
/**
 * After this many seconds without interaction the puck dims, except while a GATE breathes.
 */
quiet_after_secs: number, 
/**
 * The dimmed puck's opacity.
 */
quiet_opacity_percent: number, };
