// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One rung of the ladder the wallet recorded for a deal's deadline.
 */
export type LadderRung = "shown" | "breathing" | "notified" | "notify_suppressed" | "card_opened" | "review_opened" | "snoozed";
