// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SimulatedLine } from "./SimulatedLine";

export type MandateSimulation = { 
/**
 * The window actually replayed, Unix seconds.
 */
from: number, to: number, lines: Array<SimulatedLine>, 
/**
 * Lines whose intent could not be rebuilt from the record (both verdicts not simulated).
 */
not_simulated: number, };
