// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSlot } from "./AgentSlot";
import type { Clause } from "./Clause";
import type { MandateId } from "./MandateId";

export type MandateSignArgs = { id: MandateId | null, agent: AgentSlot, clauses: Array<Clause>, not_before: number, expires: number, };
