// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MandateSignArgs } from "./MandateSignArgs";

/**
 * What-if before signing: the draft exactly as `mandate_sign` takes it, replayed over the deals
 * recorded in a window. Read-only: nothing is signed, written or sent to PayPal.
 */
export type MandateSimulateArgs = { draft: MandateSignArgs, 
/**
 * Window start, Unix seconds. Default: seven days before `to`.
 */
from?: number | null, 
/**
 * Window end, Unix seconds. Default: now.
 */
to?: number | null, };
