// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Clause } from "./Clause";
import type { MandateId } from "./MandateId";

/**
 * The owner signs the canonical payload, excluding the signature itself.
 */
export type MandatePayload = { id: MandateId, version: number, agent_key: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], clauses: Array<Clause>, not_before: number, expires: number, };
