// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSlot } from "./AgentSlot";
import type { MandatePayload } from "./MandatePayload";
import type { Refusal } from "./Refusal";

export type MandateListEntry = { agent: AgentSlot, 
/**
 * Set when the signed policy no longer fits the wallet's rules: nothing acts under it
 * until it is signed again, and it can still be withdrawn.
 */
refusal?: Refusal | null, payload: MandatePayload, owner_sig: Array<number>, };
