// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSlot } from "./AgentSlot";
import type { MandatePayload } from "./MandatePayload";

export type MandateListEntry = { agent: AgentSlot, payload: MandatePayload, owner_sig: Array<number>, };
