// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One comparable: its lowest offer in the record's currency and the market service's id for
 * it. Typed numbers and identifiers only: no title, no merchant text.
 */
export type MarketComparable = { 
/**
 * Minor units of the certificate's currency; always above zero.
 */
minor: number, 
/**
 * The market service's id for this product, when it gave a well-formed one.
 */
product_id: string | null, };
