// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { H256 } from "./H256";
import type { Money } from "./Money";

export type MarketRef = { p25: Money, median: Money, p75: Money, retrieved_at: number, response_hash: H256, cached: boolean, };
