// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the comparables were found for the asked product. The wallet asks one way today.
 */
export type MarketMatch = "similar";
