// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSlot } from "./AgentSlot";
import type { MandateId } from "./MandateId";
import type { WatchedItem } from "./WatchedItem";

/**
 * A rule set in force with a market-watch rule (T15): the items whose market price the wallet
 * keeps fresh, and today's price checks against the rule's daily allowance. Reading market
 * prices moves no money.
 */
export type MarketWatchFact = { mandate_id: MandateId, mandate_version: number, agent: AgentSlot, items: Array<WatchedItem>, max_per_day: number, 
/**
 * Price checks made today (UTC day), counted from the audit log.
 */
used_today: number, 
/**
 * Today's allowance is used up: no price is checked again until the next UTC day.
 */
used_up: boolean, };
