// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Currency } from "./Currency";
import type { H256 } from "./H256";
import type { MarketComparable } from "./MarketComparable";
import type { MarketMatch } from "./MarketMatch";

/**
 * What a market band was computed from, kept so anyone can compute it again (market-data-2):
 * the asked product, the SHA-256 of the response bytes exactly as they arrived, how the
 * comparables were matched, and the comparables sorted by price then id.
 */
export type MarketCertificate = { product_id: string, raw_sha256: H256, match_kind: MarketMatch, currency: Currency, comparables: Array<MarketComparable>, };
