// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `Checking`: the wallet has not asked PayPal yet, or is about to ask again. `Parked`: PayPal's
 * answer could not be read or did not settle the question, so nothing more is sent for this
 * deal until it does; the deadline can only let the deal lapse or release a hold.
 */
export type MoneyCheckState = "checking" | "parked";
