// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The PayPal step a [`MoneyCheck`] is about.
 */
export type MoneyCheckStep = "create" | "authorize" | "capture" | "void";
