// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoneyCheckState } from "./MoneyCheckState";
import type { MoneyCheckStep } from "./MoneyCheckStep";

/**
 * A money step sent to PayPal whose answer never arrived or could not be read (T10). The
 * wallet reads PayPal's own record before anything else happens to the deal.
 */
export type MoneyCheck = { step: MoneyCheckStep, state: MoneyCheckState, 
/**
 * When the step was sent.
 */
since: number, 
/**
 * When the wallet asks PayPal next; null when it is not scheduled.
 */
next_check: number | null, };
