// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the due notification was not shown.
 */
export type NotifySuppression = "do_not_disturb" | "notifications_off" | "system_quiet" | "not_shown";
