// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MandatePayload } from "./MandatePayload";

export type OpenMandate = { payload: MandatePayload, owner_sig: Array<number>, };
