// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRosterEntry } from "./AgentRosterEntry";
import type { CredentialFact } from "./CredentialFact";
import type { EngineProbe } from "./EngineProbe";
import type { MarketWatchFact } from "./MarketWatchFact";
import type { ReportingPoll } from "./ReportingPoll";

/**
 * Read-only owner facts for Settings and Book: nothing here is a secret or a permission.
 */
export type OwnerFacts = { locked: boolean, 
/**
 * Seconds until the approval window idle-locks; null while it is locked.
 */
lock_in: number | null, last_reporting_poll: ReportingPoll | null, engines: Array<EngineProbe>, credentials: Array<CredentialFact>, agents: Array<AgentRosterEntry>, 
/**
 * The rule sets in force that keep market prices fresh (T15), with today's price checks.
 */
market_watch: Array<MarketWatchFact>, };
