// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { H256 } from "./H256";
import type { KeyId } from "./KeyId";

/**
 * Sent to Main after the owner confirmed the words in the approval window and Rust pinned the
 * peer. Identifiers only; the owner's local label is read from counterparty_list.
 */
export type PairingPinned = { pairing_id: H256, key_id: KeyId, house: boolean, };
