// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignedPairingIdentity } from "./SignedPairingIdentity";

export type PairingOffer = { code: string, bundle: SignedPairingIdentity, };
