// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { H256 } from "./H256";

export type PairingConfirmArgs = { pairing_id: H256, words: [string, string, string, string], display_name: string, };
