// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { H256 } from "./H256";

/**
 * Ends a pending pairing: by its id (words already on screen) or by the creator's own code
 * (waiting for a joiner). Exactly one. Aborting only restricts, so it needs no privilege.
 */
export type PairingAbortArgs = { pairing_id?: H256 | null, code?: string | null, };
