// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PayeeRef } from "./PayeeRef";
import type { Side } from "./Side";
import type { SignedPairingIdentity } from "./SignedPairingIdentity";

export type PairingJoinArgs = { code: string, 
/**
 * Omit for relay discovery; retained for explicitly offline bundle exchange.
 */
peer?: SignedPairingIdentity | null, side: Side, payee: PayeeRef, };
