// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { H256 } from "./H256";
import type { PayeeRef } from "./PayeeRef";
import type { Side } from "./Side";

export type PairingIdentity = { code_hash: H256, owner_key: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], agent_key: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], side: Side, payee: PayeeRef, expires: number, 
/**
 * A reply commits to the entire initiating identity, including payee and expiry.
 */
in_reply_to: H256 | null, };
