// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { H256 } from "./H256";
import type { HouseTable } from "./HouseTable";
import type { SignedPairingIdentity } from "./SignedPairingIdentity";

export type PairingWords = { house_table: HouseTable | null, pairing_id: H256, words: [string, string, string, string], reply: SignedPairingIdentity, };
