// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PayeeRef } from "./PayeeRef";
import type { Side } from "./Side";

export type PairingCreateArgs = { side: Side, payee: PayeeRef, };
