// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { H256 } from "./H256";

export type PendingPairing = { pairing_id: H256, words: [string, string, string, string], house: boolean, display_context: string, 
/**
 * When the signed pairing identities lapse; after it the words can no longer be confirmed.
 */
expires: number, };
