// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rect } from "./Rect";
import type { VAlign } from "./VAlign";
import type { WindowSide } from "./WindowSide";

export type Placement = { rect: Rect, side: WindowSide, valign: VAlign, };
