// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The fixed per-role system prompts a native engine starts from (compiled in from
 * `prompts/*.md`). They describe the role's tools, the table fields and the refusal codes, and
 * carry no placeholder: nothing at run time is spliced into them.
 */
export type Playbook = "buyer_haggler" | "seller_counter" | "shopper" | "shop_assistant";
