// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";
import type { Mode } from "./Mode";
import type { ProofCheckLine } from "./ProofCheckLine";

/**
 * The offline verifier's report on a proof file the owner picked. Values come from the file.
 */
export type ProofReport = { deal_id: DealId, mode: Mode, 
/**
 * The full id of the owner key the file names (64 hex characters), or "invalid".
 */
owner_key_id: string, verified: boolean, checks: Array<ProofCheckLine>, };
