// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One verifier check, keyed by its stable id; the client words it, `detail` is the verifier's own
 * line and comes from the file, so it is shown only as text.
 */
export type ProofCheckLine = { id: string, ok: boolean, detail: string, };
