// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";
import type { H256 } from "./H256";

export type QuitSummary = { confirmation_id: H256, pending: Array<DealId>, on_quit: string, };
