// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one quit line says. The first four are what will not happen while the wallet is off,
 * the last three what still happens at PayPal by itself.
 */
export type QuitEffect = "request_not_sent" | "not_collected" | "not_collected_if_approved" | "waits" | "request_runs_out" | "hold_runs_out" | "seller_may_collect";
