// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";
import type { H256 } from "./H256";
import type { QuitLine } from "./QuitLine";

export type QuitSummary = { 
/**
 * Binds the pending deals and every line below; quit_confirm refuses if any changed.
 */
confirmation_id: H256, pending: Array<DealId>, on_quit: string, 
/**
 * What will not happen while the wallet is off, one line per pending deal the forecast moves
 * money for (or that waits). None when the forecast could not be read; older shells omit it.
 */
while_off?: Array<QuitLine> | null, 
/**
 * What PayPal still does by itself (a payment request or a hold running out). None when the
 * forecast could not be read; older shells omit it.
 */
at_paypal?: Array<QuitLine> | null, };
