// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Currency } from "./Currency";
import type { DealId } from "./DealId";
import type { QuitEffect } from "./QuitEffect";

export type QuitLine = { deal_id: DealId, label: string, effect: QuitEffect, amount_minor: number, currency: Currency, 
/**
 * One plain sentence, composed here.
 */
text: string, };
