// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealEvidence } from "./DealEvidence";
import type { DealId } from "./DealId";
import type { DealState } from "./DealState";
import type { Mode } from "./Mode";

export type ReceiptEvent = { deal_id: DealId, evidence: DealEvidence, mode: Mode, state: DealState, on_silence: string, };
