// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Reconciliation = "not_applicable" | "pending_reporting" | "matched" | "mismatch";
