// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";

export type ReconcileArgs = { deal_id: DealId, start: number, end: number, };
