// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The latest own-account Transaction Search call: when, and the HTTP status PayPal answered
 * (0 = no response).
 */
export type ReportingPoll = { at: number, status: number, };
