// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemRef } from "./ItemRef";

/**
 * Watch one of the owner's own subscriptions for a failed renewal (approval, privileged). The
 * wallet reads it from PayPal every few hours, read only; a failure opens one fix that waits for
 * the owner, PayPal-reported, so what it brings in can count.
 */
export type RescueWatchArgs = { 
/**
 * The PayPal subscription id to watch.
 */
subscription_id: string, 
/**
 * The subscriber's email address a fix's invoice goes to, as the owner enters it (the
 * subscription read does not supply it).
 */
subscriber_email: string, 
/**
 * The plan, as your own item name.
 */
plan: ItemRef, };
