// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the wallet last learned about a watched subscription.
 */
export type RescueWatchState = "waiting" | "paid" | "fix_opened" | "failed_no_fix" | "cant_read";
