// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a failed renewal was learned from. `Replay` is a recorded failure the owner replayed
 * (PayPal offers no documented way to fail a sandbox renewal); its deal carries the REPLAY mode,
 * and nothing it is paid ever counts as recovered.
 */
export type RescueSource = "replay" | "paypal";
