// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Money } from "./Money";
import type { RescueView } from "./RescueView";
import type { RescueWatchView } from "./RescueWatchView";

/**
 * Every rescue, and the recovered money (one total per currency, never summed across them).
 */
export type RescueBook = { cases: Array<RescueView>, recovered: Array<Money>, 
/**
 * The owner's own subscriptions the wallet reads for a failed renewal, oldest first.
 */
watching: Array<RescueWatchView>, 
/**
 * Subscription reads made today (UTC) and the most the wallet makes in a day.
 */
watch_reads_today: number, watch_reads_max: number, };
