// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stop watching one subscription (approval, privileged). A fix it already opened is unchanged.
 */
export type RescueWatchStopArgs = { subscription_id: string, };
