// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";
import type { InvoiceText } from "./InvoiceText";
import type { RescueOffer } from "./RescueOffer";
import type { RescueSource } from "./RescueSource";

/**
 * A failed renewal and its one fix, as the wallet computed and stored it. No subscriber or
 * agent text: the invoice wording is the wallet's fixed template filled with these numbers.
 */
export type RescueView = { deal_id: DealId, source: RescueSource, offer: RescueOffer, text: InvoiceText, failed_payments: number, 
/**
 * PayPal's own next retry, when known.
 */
next_retry_at?: number | null, 
/**
 * The subscriber's address, masked ("s•••@example.com").
 */
recipient: string, 
/**
 * The PayPal invoice, once made.
 */
invoice?: string | null, 
/**
 * PayPal showed it paid and the wallet receipted it, on a failure PayPal reported: this is
 * the only money counted as recovered.
 */
counted: boolean, };
