// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemRef } from "./ItemRef";
import type { RescueWatchState } from "./RescueWatchState";

/**
 * One watched subscription, as the Rescue page and the approval window show it.
 */
export type RescueWatchView = { subscription_id: string, 
/**
 * The subscriber's address, masked ("s•••@example.com").
 */
recipient: string, plan: ItemRef, state: RescueWatchState, added_at: number, last_read_at?: number | null, next_read_at: number, };
