// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Money } from "./Money";
import type { RescueLever } from "./RescueLever";

/**
 * The one fix the wallet offers for one failed renewal: an invoice for the missed cycle at a
 * discount, inside the owner's signed fixes clause. Computed by the wallet, never by an agent.
 */
export type RescueOffer = { lever: RescueLever, 
/**
 * The missed cycle at the plan's price.
 */
cycle: Money, 
/**
 * Taken off this cycle only; the plan's price does not change.
 */
discount: Money, 
/**
 * What the invoice asks: `cycle - discount`.
 */
invoice: Money, 
/**
 * `discount` as basis points of `cycle`, rounded down. For display; the money fields bind.
 */
discount_bp: number, };
