// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemRef } from "./ItemRef";
import type { Money } from "./Money";

/**
 * A failed renewal the owner records as a labelled replay: PayPal documents no way to fail a
 * sandbox renewal. The deal carries the REPLAY mode; its invoice is real, never counted.
 */
export type RescueReplayArgs = { 
/**
 * The PayPal subscription id the failure is about.
 */
subscription_id: string, 
/**
 * The subscriber's email address the invoice goes to.
 */
subscriber_email: string, 
/**
 * The plan, as your own item name.
 */
plan: ItemRef, 
/**
 * The cycle's price at the plan.
 */
amount: Money, };
