// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RescueLever = "DISCOUNT_THIS_CYCLE" | "PAUSE" | "RETRY_AFTER_FIX" | "DOWNGRADE";
