// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Money } from "./Money";
import type { RescueView } from "./RescueView";

/**
 * Every rescue, and the recovered money (one total per currency, never summed across them).
 */
export type RescueBook = { cases: Array<RescueView>, recovered: Array<Money>, };
