// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LadderRung } from "./LadderRung";
import type { NotifySuppression } from "./NotifySuppression";

/**
 * One recorded rung, as a deal's history carries it.
 */
export type RungMark = { rung: LadderRung, at: number, reason?: NotifySuppression | null, };
