// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";
import type { EngineId } from "./EngineId";
import type { Mode } from "./Mode";
import type { RunId } from "./RunId";
import type { RunState } from "./RunState";

export type RunSnapshot = { run: RunId, deal_id: DealId, engine: EngineId, mode: Mode, state: RunState, };
