// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SafetyViolationKind = "authority" | "untracked_call" | "counterparty_text" | "refused_deal_called" | "verifier_check" | "chain_broken" | "evidence_unreadable";
