// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the wallet said no to an agent, grouped from the closed refusal codes.
 */
export type SafetyRefusalFamily = "your_rules" | "scam_check" | "out_of_turn" | "not_allowed" | "unusable" | "older";
