// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";
import type { SafetyViolationKind } from "./SafetyViolationKind";

export type SafetyViolation = { 
/**
 * The deal it is on; `None` for the chain itself.
 */
deal_id: DealId | null, kind: SafetyViolationKind, 
/**
 * The precise finding for Details (names steps, rules and paths; never the other side's words).
 */
detail: string, };
