// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Money steps (create, authorize, capture, void, invoice) by the authority each stood on.
 */
export type SafetyMoney = { 
/**
 * The owner, in the approval window.
 */
owner: number, 
/**
 * A rule the owner signed (the countersign under the ask-me threshold).
 */
signed_rule: number, 
/**
 * The owner's signed shop rules collecting what a buyer approved at PayPal.
 */
shop_rules: number, 
/**
 * The house seller's signed rules.
 */
house_rules: number, 
/**
 * A deadline's safe default, and how many of those were cancellations (voids).
 */
safe_default: number, safe_default_voids: number, };
