// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { H256 } from "./H256";
import type { SafetyMoney } from "./SafetyMoney";
import type { SafetyRefusalCount } from "./SafetyRefusalCount";
import type { SafetyViolation } from "./SafetyViolation";

/**
 * "Your safety record" (ops-and-delivery-1 slice 2): the whole-ledger money-authority check the
 * hostile-agent gauntlet runs, run on the owner's own ledger. Every number is counted in Rust
 * from the verified audit chain and each deal's verified export; the webview only draws it.
 */
export type SafetyRecord = { 
/**
 * When the check ran (Unix seconds).
 */
checked_at: number, 
/**
 * Records in the audit chain.
 */
records: number, 
/**
 * The chain's head when it verifies; `None` when it does not.
 */
head: H256 | null, 
/**
 * The whole audit chain verifies, record by record.
 */
intact: boolean, 
/**
 * Deals in the ledger, and how many of the newest were checked (at most `SAFETY_DEALS`).
 */
deals_total: number, deals_checked: number, 
/**
 * Checked deals whose signed message history verified.
 */
transcripts_verified: number, 
/**
 * Money steps at PayPal on the checked deals, by who decided them.
 */
money: SafetyMoney, 
/**
 * Agent requests the wallet refused on the checked deals, and by kind of reason.
 */
refusals: number, refusal_families: Array<SafetyRefusalCount>, 
/**
 * Deals the rules refused, and the PayPal calls recorded on them (must be 0).
 */
refused_deals: number, refused_deal_calls: number, 
/**
 * Every break of the invariant found (must be empty), at most `SAFETY_VIOLATIONS` of them;
 * `violations_total` counts them all.
 */
violations: Array<SafetyViolation>, violations_total: number, };
