// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SafetyRefusalFamily } from "./SafetyRefusalFamily";

export type SafetyRefusalCount = { family: SafetyRefusalFamily, count: number, };
