// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineId } from "./EngineId";
import type { HouseState } from "./HouseState";
import type { Mode } from "./Mode";
import type { TumblerPreferences } from "./TumblerPreferences";

export type SettingsSnapshot = { house: HouseState, mode: Mode, locked: boolean, native_reauth_available: boolean, payment_executor_configured: boolean, 
/**
 * Suppress spend/cost/stopped meters until their accounting sources are attached.
 */
meters_available: boolean, client_pending: boolean, first_run: boolean, channel3_configured: boolean, agents_paused: boolean, selected_engine: EngineId, preferences: TumblerPreferences, relay_available: boolean, 
/**
 * Lowercase hex fingerprint of the authority table this build enforces (who may call each
 * command); the same value as `AUTHORITY_MANIFEST` in `bindings/authority.ts`.
 */
authority_manifest: string, };
