// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { H256 } from "./H256";
import type { ShieldRule } from "./ShieldRule";

/**
 * The owner's release of a shield HOLD, decided in the approval window (`decided_by` human at
 * `at`). It covers the rules it names, for the terms hash it was given for, and nothing else.
 */
export type ShieldRelease = { terms_hash: H256, rules: Array<ShieldRule>, at: number, };
