// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ordered caution levels. An engine may only increase the deterministic verdict.
 */
export type ShieldVerdict = "CLEAR" | "ASK" | "HOLD" | "BLOCK";
