// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The scam shield rule that decided a verdict, in the shield's own order (report §7). Closed:
 * the deterministic rules over typed facts, and the one quarantined second opinion that can only
 * add caution. Never derived from counterparty free text.
 */
export type ShieldRule = "payee_mismatch" | "friends_and_family" | "no_market_reference" | "price_over_market" | "new_counterparty_over_threshold" | "model_caution";
