// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";
import type { DealKind } from "./DealKind";
import type { ItemRef } from "./ItemRef";
import type { Money } from "./Money";
import type { Side } from "./Side";
import type { SimulatedVerdict } from "./SimulatedVerdict";

/**
 * A recorded deal under the rules in force (`before`) and under the draft (`after`). Only
 * owner-bound facts: no counterparty words.
 */
export type SimulatedLine = { deal_id: DealId, 
/**
 * The deal's display label ("D-0193").
 */
label: string, 
/**
 * The deal's title as Main shows it (owner-bound, never counterparty words).
 */
title: string, 
/**
 * The item the deal is bound to, as the band clause names items.
 */
item_ref: ItemRef, kind: DealKind, side: Side, 
/**
 * When the deal was recorded (Unix seconds); 0 = not on record.
 */
at: number, 
/**
 * The deal total; null when the recorded terms have no valid total.
 */
amount?: Money | null, unit_price: Money, before: SimulatedVerdict, after: SimulatedVerdict, };
