// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One mandate's answer to one recorded intent, from `MandatePayload::check` itself.
 */
export type SimulatedVerdict = { "type": "allow" } | { "type": "ask", clause: number, } | { "type": "refuse", clause: number, reason: string, } | { "type": "not_simulated" };
