// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Snap = "main_right" | "main_left" | "main_corner" | "screen_left" | "screen_right" | "free";
