// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Currency } from "./Currency";
import type { Delivery } from "./Delivery";
import type { ItemRef } from "./ItemRef";
import type { Money } from "./Money";

export type Terms = { item_ref: ItemRef, qty: number, unit_price: Money, currency: Currency, delivery: Delivery, };
