// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Money } from "./Money";
import type { TranscriptBy } from "./TranscriptBy";
import type { TranscriptType } from "./TranscriptType";

export type TranscriptStep = { seq: number, by: TranscriptBy, typ: TranscriptType, price: Money | null, at: number, verified: boolean, };
