// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Form } from "./Form";

export type TumblerStatus = { visible: boolean, form: Form, count: number, };
