// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TumblerAction = "review" | "withdraw" | "let_lapse" | "snooze30" | "open_in_table";
