// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Form } from "./Form";
import type { PuckPosition } from "./PuckPosition";
import type { Snap } from "./Snap";

export type TumblerPreferences = { pinned: boolean, position: PuckPosition | null, form: Form, quiet: boolean, dnd: boolean, notifications: boolean, snap: Snap, };
