// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealId } from "./DealId";

export type TumblerHandoff = { deal_id: DealId, approve_until: number, };
