// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Currency } from "./Currency";
import type { Money } from "./Money";

/**
 * The owner's wallet-wide limits, signed with the owner key over
 * [`WalletEnvelope::signing_bytes`]. Versions are append-only; the newest is in force.
 */
export type WalletEnvelope = { version: number, currency: Currency, 
/**
 * Most the agents may pay out in one UTC day (the day's budget, as clause 5 counts it).
 */
max_out_day: Money, 
/**
 * Most held at PayPal or agreed and about to be, at once.
 */
max_held: Money, 
/**
 * Most deals that may agree in one UTC day.
 */
max_deals_day: number, expires: number, };
