[package]
name = "rendezvous"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
axum.workspace = true
tokio.workspace = true
async-trait.workspace = true
serde.workspace = true
thiserror.workspace = true
table-core.workspace = true
table-relay = { path = "../../crates/table-relay" }
getrandom.workspace = true

[dev-dependencies]
tower = {version="0.5",features=["util"]}
serde_json.workspace = true
