[package]
name = "table-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
serde_jcs.workspace = true
thiserror.workspace = true
sha2.workspace = true
ulid.workspace = true
ts-rs.workspace = true

[lints]
workspace = true
